// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjyzakkwpmhcmbqeihjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqeXpha2t3cG1oY21icWVpaGpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDMzMzQsImV4cCI6MjA3MzUxOTMzNH0._klUC3w94AjN2JDmDwqoxeRC_yLfVCwT_heIKRk4_Zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});